name: JUST Print
on:
  push:
    branches: "**"
env:
  ENVIRONAME: 'madawaki'  

jobs:
  PrintJob1:

    runs-on: ubuntu-latest

    steps:
    - run: echo "This is the value ${{ env.ENVIRONAME }}. Thanks."  
